/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author chris
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IDcompra = new javax.swing.JTextField();
        BTsalvar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        IDlista = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        BTlistar = new javax.swing.JToggleButton();
        BTordenar = new javax.swing.JToggleButton();
        BTexcluir = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setText("lista de supermercado");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 519, 40));

        jLabel2.setFont(new java.awt.Font("Candara Light", 1, 10)); // NOI18N
        jLabel2.setText("item de compra");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));
        jPanel1.add(IDcompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 320, -1));

        BTsalvar.setBackground(new java.awt.Color(204, 0, 0));
        BTsalvar.setText("salvar");
        BTsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsalvarActionPerformed(evt);
            }
        });
        jPanel1.add(BTsalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 90, -1));

        IDlista.setColumns(20);
        IDlista.setFont(new java.awt.Font("Candara Light", 1, 10)); // NOI18N
        IDlista.setForeground(new java.awt.Color(204, 0, 0));
        IDlista.setRows(5);
        jScrollPane1.setViewportView(IDlista);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 580, -1));

        jLabel3.setFont(new java.awt.Font("Candara Light", 1, 10)); // NOI18N
        jLabel3.setText("lista de compras");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        BTlistar.setBackground(new java.awt.Color(255, 0, 0));
        BTlistar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTlistar.setText("listar");
        BTlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTlistarActionPerformed(evt);
            }
        });
        jPanel1.add(BTlistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 90, -1));

        BTordenar.setBackground(new java.awt.Color(204, 0, 0));
        BTordenar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTordenar.setText("ordenar");
        BTordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTordenarActionPerformed(evt);
            }
        });
        jPanel1.add(BTordenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 90, -1));

        BTexcluir.setBackground(new java.awt.Color(204, 0, 0));
        BTexcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTexcluir.setText("excluir");
        BTexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTexcluirActionPerformed(evt);
            }
        });
        jPanel1.add(BTexcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 90, -1));

        jToggleButton4.setBackground(new java.awt.Color(204, 0, 0));
        jToggleButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jToggleButton4.setText("Eliminar lista");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     ArrayList<String> listac = new ArrayList<String>();
    private void BTsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsalvarActionPerformed
     listac.add(IDcompra.getText());
        JOptionPane.showMessageDialog(null,"item de compra foi salva");
      IDcompra.setText(null);
      IDcompra.requestFocus();
    }//GEN-LAST:event_BTsalvarActionPerformed

    private void BTlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTlistarActionPerformed
     
        String com ="";
        for(int i=0; i<listac.size();i++){
           com = com +listac.get(i)+"\n";
          
       }
        IDlista.setText(com);
    }//GEN-LAST:event_BTlistarActionPerformed

    private void BTordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTordenarActionPerformed
      if(!listac.isEmpty() && listac.size()>=2){  
        Collections.sort(listac);
      }else if(listac.size()==1){
       JOptionPane.showMessageDialog(null, "não tem item suficiente ");
       
       }else{
       
           JOptionPane.showMessageDialog(null, "a lista esta vazia ");
       
       }
    }//GEN-LAST:event_BTordenarActionPerformed

    private void BTexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTexcluirActionPerformed
       if(listac.isEmpty()){
       JOptionPane.showMessageDialog(null,"sua lista esta vazia");
       
       }else{
        int i= Integer.parseInt(JOptionPane.showInputDialog("qual item desaja excluir"));
       if(i>0 && i<listac.size()){
       listac.remove(i-1);
       JOptionPane.showMessageDialog(null, "item excluido");
       }else{
       JOptionPane.showMessageDialog(null, "não existe esse item");
       }
       }
        
        
    }//GEN-LAST:event_BTexcluirActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
       if(listac.isEmpty()) {
       JOptionPane.showMessageDialog(null, "não tem item para apagar");
       }else{
      
        listac.clear();
       JOptionPane.showMessageDialog(null, "lista apagada");
       }
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BTexcluir;
    private javax.swing.JToggleButton BTlistar;
    private javax.swing.JToggleButton BTordenar;
    private javax.swing.JToggleButton BTsalvar;
    private javax.swing.JTextField IDcompra;
    private javax.swing.JTextArea IDlista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables
}
